import type { Metadata } from "next";

import {
  defaultLocale,
  locales,
  ogLocale,
  type AppLocale,
} from "@/i18n/locales";
import { siteConfig } from "@/lib/site";

type PageMetadataInput = {
  title: string;
  description: string;
  /** Route path beginning with "/", without a locale prefix, e.g. "/for-creators" */
  path: string;
  locale: AppLocale;
  ogType?: "website" | "article" | "profile";
  /**
   * Skip hreflang alternates. Use for noindex surfaces (creator pages, gift
   * confirmations) where alternate-language hints are pointless.
   */
  noHreflang?: boolean;
  /**
   * Keep the page out of search engines (`robots: noindex, nofollow`). Used
   * for the legal pages (privacy, terms, Impressum, accessibility) so the
   * operator's name and address don't surface in search results. Implies
   * `noHreflang` — a noindex page shouldn't advertise language alternates.
   */
  noindex?: boolean;
};

/** "/de" + path, with the bare root collapsing to "/de". */
export function localizedPath(path: string, locale: AppLocale): string {
  return path === "/" ? `/${locale}` : `/${locale}${path}`;
}

/** Absolute, self-referencing canonical URL for a locale-prefixed route. */
export function canonicalUrl(path: string, locale: AppLocale): string {
  const base = siteConfig.url.replace(/\/$/, "");
  return `${base}${localizedPath(path, locale)}`;
}

/**
 * hreflang map for an indexable route: every supported locale plus
 * x-default pointing at the English URL.
 */
export function hreflangAlternates(path: string): Record<string, string> {
  return {
    ...Object.fromEntries(
      locales.map((locale) => [locale, canonicalUrl(path, locale)]),
    ),
    "x-default": canonicalUrl(path, defaultLocale),
  };
}

/**
 * Default social-sharing image (generated by app/opengraph-image.tsx).
 * Referenced explicitly because a page-level `openGraph` object replaces the
 * root layout's, which would otherwise drop the file-convention image.
 */
const defaultOgImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "BuyMeATee — For Golfers With a Goal. Where golfers raise support for their journey.",
};

/**
 * Build unique, accurate metadata for a route in a given locale.
 * Canonicals are self-referencing per locale — a German page must never
 * canonicalise to the English version.
 */
export function pageMetadata({
  title,
  description,
  path,
  locale,
  ogType = "website",
  noHreflang = false,
  noindex = false,
}: PageMetadataInput): Metadata {
  const url = canonicalUrl(path, locale);
  // A noindex page must not advertise language alternates either.
  const skipHreflang = noHreflang || noindex;
  return {
    title,
    description,
    ...(noindex ? { robots: { index: false, follow: false } } : {}),
    alternates: {
      canonical: url,
      ...(skipHreflang ? {} : { languages: hreflangAlternates(path) }),
    },
    openGraph: {
      title,
      description,
      url,
      siteName: siteConfig.name,
      locale: ogLocale[locale],
      alternateLocale: skipHreflang
        ? undefined
        : locales.filter((l) => l !== locale).map((l) => ogLocale[l]),
      type: ogType,
      images: [defaultOgImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

/** Root metadata for app/[locale]/layout.tsx. */
export function rootMetadata(
  locale: AppLocale,
  {
    title = siteConfig.defaultTitle,
    description = siteConfig.description,
  }: { title?: string; description?: string } = {},
): Metadata {
  return {
    metadataBase: new URL(siteConfig.url),
    title: {
      default: title,
      template: siteConfig.titleTemplate,
    },
    description,
    alternates: {
      canonical: canonicalUrl("/", locale),
      languages: hreflangAlternates("/"),
    },
    openGraph: {
      title,
      description,
      url: canonicalUrl("/", locale),
      siteName: siteConfig.name,
      locale: ogLocale[locale],
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}
