import type { Metadata } from "next";

import { siteConfig } from "@/lib/site";

type PageMetadataInput = {
  title: string;
  description: string;
  /** Route path beginning with "/", e.g. "/for-creators" */
  path: string;
  ogType?: "website" | "article";
};

/** Absolute canonical URL for a route path. */
export function canonicalUrl(path: string): string {
  const base = siteConfig.url.replace(/\/$/, "");
  return path === "/" ? `${base}/` : `${base}${path}`;
}

/**
 * Default social-sharing image (generated by app/opengraph-image.tsx).
 * Referenced explicitly because a page-level `openGraph` object replaces the
 * root layout's, which would otherwise drop the file-convention image.
 */
const defaultOgImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "BuyMeATee — Support the journey. Where golf fans help creators chase their goals.",
};

/**
 * Build unique, accurate metadata for a route.
 * Title is passed through the root layout's title template.
 */
export function pageMetadata({
  title,
  description,
  path,
  ogType = "website",
}: PageMetadataInput): Metadata {
  const url = canonicalUrl(path);
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type: ogType,
      images: [defaultOgImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

/** Root metadata for app/layout.tsx. */
export function rootMetadata(): Metadata {
  return {
    metadataBase: new URL(siteConfig.url),
    title: {
      default: siteConfig.defaultTitle,
      template: siteConfig.titleTemplate,
    },
    description: siteConfig.description,
    alternates: { canonical: canonicalUrl("/") },
    openGraph: {
      title: siteConfig.defaultTitle,
      description: siteConfig.description,
      url: canonicalUrl("/"),
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: siteConfig.defaultTitle,
      description: siteConfig.description,
    },
  };
}
